name: onboarding_repository
description: Repository for managing onboarding data
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ^3.27.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
