name: structures_repository
description: A repository that handles structure related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  structures_api:
    path: ../structures_api

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
