name: happy_day
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dots_indicator: ^3.0.0
  easy_date_timeline: ^1.1.3
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.4.1
  intl: ^0.19.0
  local_storage_structures_api:
    path: packages/local_storage_structures_api
  shared_preferences: ^2.3.3
  simple_circular_progress_bar: ^1.0.2
  skeletonizer: ^1.4.2
  structures_api:
    path: packages/structures_api
  structures_repository:
    path: packages/structures_repository
  toastification: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
