name: happy_day
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  confetti: ^0.8.0
  easy_date_timeline: ^2.0.6
  email_repository:
    path: packages/email_repository
  firebase_analytics: ^11.4.0
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.0
  firebase_vertexai: ^1.1.1
  flex_color_picker: ^3.7.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_fimber: ^0.7.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  intl: ^0.19.0
  local_storage_structures_api:
    path: packages/local_storage_structures_api
  onboarding_repository:
    path: packages/onboarding_repository
  path_provider: ^2.1.5
  reorderables: ^0.6.0
  shared_preferences: ^2.5.2
  simple_circular_progress_bar: ^1.0.2
  skeletonizer: ^1.4.3
  step_progress_indicator: ^1.0.2
  steps_generation_repository:
    path: packages/steps_generation_repository
  structures_api:
    path: packages/structures_api
  structures_repository:
    path: packages/structures_repository
  toastification: ^2.3.0
  wiredash: ^2.4.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/app_icon/app-icon.png"
  adaptive_icon_background: "assets/app_icon/app-icon-background.png"
  adaptive_icon_foreground: "assets/app_icon/app-icon-foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app_icon/
    - assets/vectors/
