name: steps_generation_repository
description: Client and repository for generating structures steps
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ^3.27.2

dependencies:
  firebase_vertexai: ^1.1.1
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
