// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACunuY8lvLvlmRPHJFFNDtCITFR5BzJtg',
    appId: '1:311862406648:web:23836fd3316ff2b7587a0d',
    messagingSenderId: '311862406648',
    projectId: 'happy-day-dev',
    authDomain: 'happy-day-dev.firebaseapp.com',
    storageBucket: 'happy-day-dev.firebasestorage.app',
    measurementId: 'G-G5WP416SD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuow_P5CbpFKqowN0aYMFFRzLJqF9Vb04',
    appId: '1:311862406648:android:bf7e6a3f24a22760587a0d',
    messagingSenderId: '311862406648',
    projectId: 'happy-day-dev',
    storageBucket: 'happy-day-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7izXzH4qxd5pD_8LT30HUeeporEQ7G0',
    appId: '1:311862406648:ios:ee523623fe640d18587a0d',
    messagingSenderId: '311862406648',
    projectId: 'happy-day-dev',
    storageBucket: 'happy-day-dev.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.happy-day.dev',
  );
}
