// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqAnqCzA_MzhDRzzy6uctf119NyrrD-qg',
    appId: '1:355750949707:web:1c03495d6a916049982ece',
    messagingSenderId: '355750949707',
    projectId: 'happy-day-prod',
    authDomain: 'happy-day-prod.firebaseapp.com',
    storageBucket: 'happy-day-prod.firebasestorage.app',
    measurementId: 'G-XLLDDEW505',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlfjNqYMmVwPfyP4fBmqTSLyOYPK0KRyE',
    appId: '1:355750949707:android:b573466e58672fe4982ece',
    messagingSenderId: '355750949707',
    projectId: 'happy-day-prod',
    storageBucket: 'happy-day-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSo40O2xD2hKP2tDI__dWFPHxuoTcrSt0',
    appId: '1:355750949707:ios:c27847143509e6e4982ece',
    messagingSenderId: '355750949707',
    projectId: 'happy-day-prod',
    storageBucket: 'happy-day-prod.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.happy-day',
  );
}
