// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAApWSzHCU9htqYCRBBgTfEfcJPELjHLw',
    appId: '1:881917110490:web:bef60608e64c1c393edde3',
    messagingSenderId: '881917110490',
    projectId: 'happy-day-stg',
    authDomain: 'happy-day-stg.firebaseapp.com',
    storageBucket: 'happy-day-stg.firebasestorage.app',
    measurementId: 'G-6MZJCQQYE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdzgrbBAndsjnULAfkr1TejbRo-jPA4w',
    appId: '1:881917110490:android:552eb26966f6d2d73edde3',
    messagingSenderId: '881917110490',
    projectId: 'happy-day-stg',
    storageBucket: 'happy-day-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JbJto3tDfryoJuYyI8vLKHmxrN3JWAI',
    appId: '1:881917110490:ios:5be7202e7dbd36a93edde3',
    messagingSenderId: '881917110490',
    projectId: 'happy-day-stg',
    storageBucket: 'happy-day-stg.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.happy-day.stg',
  );

}