// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP5Qep9NFaUsX6iG-GMOiDt75tz45DRlc',
    appId: '1:86462327884:web:f4c6e5bca04b43c81e58e9',
    messagingSenderId: '86462327884',
    projectId: 'happy-day-44b11',
    authDomain: 'happy-day-44b11.firebaseapp.com',
    storageBucket: 'happy-day-44b11.firebasestorage.app',
    measurementId: 'G-79L455G7YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ykiIHR5lvCjFTEfNPtp8y4ffSZJ8FHM',
    appId: '1:86462327884:android:cab0e1f29bcfb5331e58e9',
    messagingSenderId: '86462327884',
    projectId: 'happy-day-44b11',
    storageBucket: 'happy-day-44b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWwGemdmDFKHbi4Uo3iPAAk1qxuAVrhsE',
    appId: '1:86462327884:ios:47b616fd5a830f451e58e9',
    messagingSenderId: '86462327884',
    projectId: 'happy-day-44b11',
    storageBucket: 'happy-day-44b11.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.happy-day',
  );
}
