name: calendar_day_structures_api
description: The interface and models for an API providing access to calendar day structures.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.11.0
  path_provider: ^2.1.5
  structures_api:
    path: ../structures_api
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0