name: structures_api
description: The interface and models for an API providing access to structures.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
