name: local_storage_structures_api
description: A Flutter implementation of the StructuresApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.27.5
  shared_preferences: ^2.3.3
  structures_api:
    path: ../structures_api

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
