name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --line-length 80 --set-exit-if-changed $(find lib test -name "*.dart" ! -name "firebase_options_*.dart")
