name: happy_day

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      min_coverage: 10
      setup: |
        echo "Creating dummy Firebase options files for CI..."
        echo "
        import 'package:firebase_core/firebase_core.dart';
        
        class DefaultFirebaseOptions {
          static const FirebaseOptions currentPlatform = FirebaseOptions(
            apiKey: 'dummy',
            appId: 'dummy',
            messagingSenderId: 'dummy',
            projectId: 'dummy',
          );
        }" > lib/firebase_options_dev.dart
        cp lib/firebase_options_dev.dart lib/firebase_options_stg.dart
        cp lib/firebase_options_dev.dart lib/firebase_options_prod.dart

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
